import { PrismaClient } from "@prisma/client"
const db = new PrismaClient()
const users = await db.user.findMany({ where: { deletedAt: null }, select: { id: true, username: true, role: true, idleTimeoutMinutes: true, idleTimeoutLocked: true } })
const um = new Map(users.map(u => [u.id, u.username]))
const wss = await db.browserWorkspace.findMany({ where: { deletedAt: null }, select: { id: true, name: true, idleTimeoutMinutes: true, ttlMinutes: true, userId: true, createdByUserId: true } })
console.log("workspaces:", JSON.stringify(wss.map(w => ({ name: w.name, owner: um.get(w.userId), idle: w.idleTimeoutMinutes, ttl: w.ttlMinutes })), null, 1))
console.log("users:", JSON.stringify(users.map(u => ({ username: u.username, role: u.role, idle: u.idleTimeoutMinutes, locked: u.idleTimeoutLocked }))))
const groups = await db.group.findMany({ where: { deletedAt: null }, select: { id: true, name: true, idleTimeoutMinutes: true, idleTimeoutLocked: true } })
console.log("groups:", JSON.stringify(groups))
const gids = groups.map(g => g.id)
const memberships = await db.groupUser.findMany({ select: { groupId: true, userId: true } })
console.log("memberships:", JSON.stringify(memberships.map(m => ({ group: groups.find(g => g.id === m.groupId)?.name, user: um.get(m.userId) }))))
const crx = await db.crxPlugin.findMany({ select: { crxId: true, name: true, enabled: true, deletedAt: true } })
console.log("crxPlugins:", JSON.stringify(crx))
await db.$disconnect()
